"""ComfyUI nodes for planning and writing MiniMax H3 prompts."""

if __package__:
    from .enhancer import (
        NODE_CLASS_MAPPINGS as ENHANCER_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as ENHANCER_NODE_DISPLAY_NAME_MAPPINGS,
    )
    from .nodes import (
        NODE_CLASS_MAPPINGS as GUIDE_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as GUIDE_NODE_DISPLAY_NAME_MAPPINGS,
    )
else:  # Allows direct loading by test runners from a hyphenated folder.
    from enhancer import (
        NODE_CLASS_MAPPINGS as ENHANCER_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as ENHANCER_NODE_DISPLAY_NAME_MAPPINGS,
    )
    from nodes import (
        NODE_CLASS_MAPPINGS as GUIDE_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as GUIDE_NODE_DISPLAY_NAME_MAPPINGS,
    )

NODE_CLASS_MAPPINGS = {**GUIDE_NODE_CLASS_MAPPINGS, **ENHANCER_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **GUIDE_NODE_DISPLAY_NAME_MAPPINGS,
    **ENHANCER_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
